import {
  claimSensorRun,
  readHookState,
  writeHookState,
  insertTaskIfNew,
  createSensorLogger,
  fetchWithRetry,
} from "../../src/sensors.ts";
import { initDatabase } from "../../src/db.ts";

const SENSOR_NAME = "daily-brief-compile";
const POLL_INTERVAL = 30; // check every 30 min
const TARGET_HOUR_PST = 21; // 9 PM PST — 2 hours before inscription at 11 PM
const MIN_SIGNALS = 3; // minimum approved signals to compile
const TASK_SOURCE = "sensor:daily-brief-compile";
const API_BASE = "https://aibtc.news/api";
const log = createSensorLogger(SENSOR_NAME);

function getPSTInfo(now: Date): { hour: number; date: string } {
  const hour = parseInt(
    new Intl.DateTimeFormat("en-US", {
      timeZone: "America/Los_Angeles",
      hour: "numeric",
      hour12: false,
    }).format(now),
    10
  );
  const date = new Intl.DateTimeFormat("en-CA", {
    timeZone: "America/Los_Angeles",
  }).format(now); // YYYY-MM-DD
  return { hour, date };
}

export default async function dailyBriefCompileSensor(): Promise<string> {
  initDatabase();

  const claimed = await claimSensorRun(SENSOR_NAME, POLL_INTERVAL);
  if (!claimed) return "skip";

  const now = new Date();
  const { hour, date: pstDate } = getPSTInfo(now);

  // Only fire at 9 PM PST
  if (hour !== TARGET_HOUR_PST) return "skip";

  // Dedup: only fire once per PST calendar day
  const state = await readHookState(SENSOR_NAME);
  if (state?.lastCompiledDate === pstDate) return "skip";

  // Check if there are enough approved signals to compile
  let signalCount = 0;
  try {
    const resp = await fetchWithRetry(`${API_BASE}/signals?status=approved`);
    if (!resp.ok) {
      log(`API returned ${resp.status} checking signals`);
      return "error";
    }
    const data = (await resp.json()) as { signals?: unknown[] };
    signalCount = data.signals?.length ?? 0;
  } catch (err) {
    log(`Fetch error: ${err instanceof Error ? err.message : String(err)}`);
    return "error";
  }

  if (signalCount < MIN_SIGNALS) {
    log(`Only ${signalCount} approved signal(s), need ${MIN_SIGNALS} — skipping compilation`);
    // Do NOT update lastCompiledDate — check again tomorrow if signals arrive late
    return "ok";
  }

  // Check if brief was already compiled today (idempotency — someone may have compiled manually)
  try {
    const resp = await fetchWithRetry(`${API_BASE}/brief/${pstDate}`);
    if (resp.ok) {
      const data = (await resp.json()) as { compiledAt?: string | null };
      if (data.compiledAt) {
        log(`Brief for ${pstDate} already compiled at ${data.compiledAt} — skipping`);
        await writeHookState(SENSOR_NAME, {
          ...(state ?? { version: 0 }),
          last_ran: now.toISOString(),
          last_result: "ok",
          version: (state?.version ?? 0) + 1,
          lastCompiledDate: pstDate,
        });
        return "ok";
      }
    }
  } catch {
    // Non-fatal — proceed to create compile task even if check fails
  }

  log(`${signalCount} approved signal(s) ready — queuing compilation for ${pstDate}`);

  await writeHookState(SENSOR_NAME, {
    ...(state ?? { version: 0 }),
    last_ran: now.toISOString(),
    last_result: "ok",
    version: (state?.version ?? 0) + 1,
    lastCompiledDate: pstDate,
  });

  const id = insertTaskIfNew(TASK_SOURCE, {
    subject: `Compile daily brief for ${pstDate}`,
    description: [
      `Compile the aibtc.news daily brief for ${pstDate}.`,
      ``,
      `## Steps`,
      `1. Run: arc skills run --name aibtc-news-editorial -- compile-brief --date ${pstDate}`,
      `2. Verify: the command calls POST /api/brief/compile with BIP-137 auth`,
      `3. On success: the backend transitions approved signals to brief_included (backend-owned status)`,
      `4. Earnings of 30,000 sats per signal are auto-generated by the API`,
      ``,
      `Close as completed on success. Close as failed if compile-brief errors.`,
    ].join("\n"),
    priority: 5,
    skills: JSON.stringify(["aibtc-news-editorial", "bitcoin-wallet"]),
  });

  return id !== null ? "ok" : "skip";
}
