import {
  claimSensorRun,
  readHookState,
  writeHookState,
  insertTaskIfNew,
  createSensorLogger,
  fetchWithRetry,
} from "../../src/sensors.ts";
import { initDatabase } from "../../src/db.ts";

import { getUTCInfo } from "../../src/time.ts";

const SENSOR_NAME = "daily-brief-compile";
const POLL_INTERVAL = 30; // check every 30 min
const TARGET_HOUR_UTC = 5; // 05:00 UTC — 2 hours before inscription at 07:00 UTC
const MIN_SIGNALS = 1; // minimum approved signals to compile (closed-loop: 1 signal = publish)
const TASK_SOURCE = "sensor:daily-brief-compile";
const API_BASE = "https://aibtc.news/api";
const log = createSensorLogger(SENSOR_NAME);

export default async function dailyBriefCompileSensor(): Promise<string> {
  initDatabase();

  const claimed = await claimSensorRun(SENSOR_NAME, POLL_INTERVAL);
  if (!claimed) return "skip";

  const now = new Date();
  const { hour, date: utcDate } = getUTCInfo(now);

  // Only fire at 05:00 UTC
  if (hour !== TARGET_HOUR_UTC) return "skip";

  // Brief covers the previous UTC day (sensor fires after yesterday ends)
  const yesterdayUTC = new Date(now);
  yesterdayUTC.setUTCDate(yesterdayUTC.getUTCDate() - 1);
  const briefDate = yesterdayUTC.toISOString().slice(0, 10);

  // Dedup: only fire once per UTC calendar day (keyed on today's date, not yesterday's)
  const state = await readHookState(SENSOR_NAME);
  if (state?.lastCompiledDate === utcDate) return "skip";

  // Check if brief was already compiled (idempotency — someone may have compiled manually)
  try {
    const resp = await fetchWithRetry(`${API_BASE}/brief/${briefDate}`);
    if (resp.ok) {
      const data = (await resp.json()) as { compiledAt?: string | null };
      if (data.compiledAt) {
        log(`Brief for ${briefDate} already compiled at ${data.compiledAt} — skipping`);
        await writeHookState(SENSOR_NAME, {
          ...(state ?? { version: 0 }),
          last_ran: now.toISOString(),
          last_result: "ok",
          version: (state?.version ?? 0) + 1,
          lastCompiledDate: utcDate,
        });
        return "ok";
      }
    }
  } catch {
    // Non-fatal — proceed to create compile task even if check fails
  }

  // Check if there are enough approved signals to compile
  let signalCount = 0;
  try {
    const resp = await fetchWithRetry(`${API_BASE}/signals?status=approved&date=${briefDate}`);
    if (!resp.ok) {
      log(`API returned ${resp.status} checking signals for ${briefDate}`);
      return "error";
    }
    const data = (await resp.json()) as { signals?: unknown[] };
    signalCount = data.signals?.length ?? 0;
  } catch (err) {
    log(`Fetch error: ${err instanceof Error ? err.message : String(err)}`);
    return "error";
  }

  if (signalCount < MIN_SIGNALS) {
    log(`Only ${signalCount} approved signal(s) for ${briefDate}, need ${MIN_SIGNALS} — skipping compilation`);
    // Do NOT update lastCompiledDate — check again if signals arrive
    return "ok";
  }

  log(`${signalCount} approved signal(s) ready — queuing compilation for ${briefDate}`);

  await writeHookState(SENSOR_NAME, {
    ...(state ?? { version: 0 }),
    last_ran: now.toISOString(),
    last_result: "ok",
    version: (state?.version ?? 0) + 1,
    lastCompiledDate: utcDate,
  });

  const id = insertTaskIfNew(TASK_SOURCE, {
    subject: `Compile daily brief for ${briefDate}`,
    description: [
      `Compile the aibtc.news daily brief for ${briefDate}.`,
      ``,
      `## Steps`,
      `1. Run: arc skills run --name aibtc-news-editorial -- compile-brief --date ${briefDate}`,
      `2. Verify: the command calls POST /api/brief/compile with BIP-137 auth`,
      `3. On success: the backend transitions approved signals to brief_included (backend-owned status)`,
      `4. Earnings of 30,000 sats per signal are auto-generated by the API`,
      ``,
      `Close as completed on success. Close as failed if compile-brief errors.`,
    ].join("\n"),
    priority: 5,
    skills: JSON.stringify(["aibtc-news-editorial", "bitcoin-wallet"]),
  });

  return id !== null ? "ok" : "skip";
}
